apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ${TDP_NAMESPACE}
  namespace: ${ARGOCD_NAMESPACE}
spec:
  description: Tecnisys Data Platform

  sourceNamespaces:
    - ${TDP_PROJECT_NAMESPACE}
    
  sourceRepos:
    - '*'

  destinations:
    - server: https://kubernetes.default.svc
      namespace: '*'

  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'

  orphanedResources:
    warn: false
